name: CI
on:
    pull_request:
        branches:
            - main
    push:
        branches:
            - main

jobs:
    build-and-test:
        name: Build and Test
        runs-on: ubuntu-latest
        #if github.ref == 'refs/heads/main'
        steps:
            - uses: actions/checkout@v3
            - name: Install dependencies
              run: npm ci
            - name: Run Lint
              run: npm run lint
            - name: Test & Coverage
              run: npm run test
              env:
                  DB_HOST: ${{ secrets.DB_HOST }}
                  DB_USERNAME: ${{ secrets.DB_USERNAME }}
                  DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
                  DB_NAME: ${{ secrets.DB_NAME }}
                  DB_PORT: ${{ secrets.DB_PORT }}
                  PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
                  JWKS_URI: ${{ secrets.JWKS_URI }}
                  REFRESH_TOKEN_SECRET: ${{ secrets.REFRESH_TOKEN_SECRET }}
            - name: Build-ts
              run: npm run build
            - name: SonarCloud Scan
              uses: SonarSource/sonarcloud-github-action@master
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

    build-and-push-docker:
        name: Build and Push Docker
        neeeds: build-and-test
        runs-on: ubuntu-latest
        env:
            IMAGE_NAME: devsuvamjyoti/pizza-auth-service
            IMAGE_TAG: build-${{ github.nun_number }}
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3
            - name: Login to Docker Hub
              uses: docker/login-action@v1
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_PASSWORD }}
            - name: Build Docker image
              run: docker build -t ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} -f docker/prod/Dockerfile .
            - name: Push Docker image
              run: docker push ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
